-- AlterTable
ALTER TABLE "Account" ALTER COLUMN "startDate" SET DATA TYPE DATE,
ALTER COLUMN "cutDate" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "Billing" ALTER COLUMN "startDate" SET DATA TYPE DATE,
ALTER COLUMN "endDate" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "Consultations" ALTER COLUMN "requestDate" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "Tasks" ALTER COLUMN "createdAt" SET DATA TYPE DATE,
ALTER COLUMN "updatedAt" SET DATA TYPE DATE,
ALTER COLUMN "dueDate" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
